version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: |
          java --version

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
